name: my_sdk
description: A simple Dart SDK for string and math utilities.
version: 1.0.0
homepage: https://github.com/MohdAmeer527/my_sdk
repository: https://github.com/MohdAmeer527/my_sdk.git

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
